### ISSUE TITLE
実行時に関数が無いとのエラーが出るため実行することができません

### ISSUE THREAD

**Issue by Jamu2800** [y-chan/voicevox_discord_tts_bot#1]
### 困っていること
実行時に以下のエラーが出てしまいます。
```
> voicevox_discord_tts_bot@0.2.0 start
> ts-node -r tsconfig-paths/register index.ts

/home/jamu/voicevox_discord_tts_bot/node_modules/node-voicevox-engine/index.js:28
        this.addon = new addon(__dirname + '/open_jtalk_dic_utf_8-1.11/', __dirname + '/default.csv', user_dict_root, coreFilePath, useGpu);
                     ^
Error: to load library is succeeded, but can't found needed functions
    at new Engine (/home/jamu/voicevox_discord_tts_bot/node_modules/node-voicevox-engine/index.js:28:22)
    at new TextToSpeechBot (/home/jamu/voicevox_discord_tts_bot/src/textToSpeechBot.ts:228:19)
    at new Client (/home/jamu/voicevox_discord_tts_bot/src/client.ts:8:45)
    at Object.<anonymous> (/home/jamu/voicevox_discord_tts_bot/index.ts:21:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/jamu/voicevox_discord_tts_bot/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jamu/voicevox_discord_tts_bot/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
```

### 実行環境
WindowsのWSL上のUbuntuで動かしています
WSL バージョン: 1.0.0.0
カーネル バージョン: 5.15.74.2
WSLg バージョン: 1.0.47
MSRDC バージョン: 1.2.3575
Direct3D バージョン: 1.606.4
DXCore バージョン: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windowsバージョン: 10.0.22621.819
Ubuntuバージョン:  Ubuntu 22.04.1 LTS

### 環境づくり
以下のシェルスクリプトを実行しています
`npm install`だけうまくいかないので手動で行ってください
```
#!/bin/bash
echo "apt update"
apt -qq update
echo "apt upgrade"
apt -y -qq upgrade
echo "apt install git-all nodejs npm unzip"
apt install -y -qq git-all nodejs npm unzip
echo "npm install n"
npm install -g n
n lts

THIS_DIR=`pwd`
HOME_DIR="/home/${SUDO_USER}/"

# voicevox_discord_tts_bot install
echo "tts bot install"
BOT_URL="https://github.com/y-chan/voicevox_discord_tts_bot.git"
BOT_DIR="${THIS_DIR}/voicevox_discord_tts_bot/"
cd ${THIS_DIR}
git clone ${BOT_URL}
# cd ${BOT_DIR}
# npm install

# libtorch install
echo "libtorch install"
LIBTORCH_URL="https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.1%2Bcpu.zip"
LIBTORCH_FILE_NAME="libtorch"
cd ${THIS_DIR}
wget ${LIBTORCH_URL} -O "${LIBTORCH_FILE_NAME}.zip"
unzip ${LIBTORCH_FILE_NAME}
cd ${HOME_DIR}
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${THIS_DIR}/libtorch/lib" >> /etc/environment

# VOICEVOX CORE intstall
echo "core install"
CORE_URL="https://github.com/VOICEVOX/voicevox_core/releases/download/0.9.4/core.zip"
CORE_FILE_NAME="voicevox_core"
OPEN_JTALK_DICT_URL="https://jaist.dl.sourceforge.net/project/open-jtalk/Dictionary/open_jtalk_dic-1.11/open_jtalk_dic_utf_8-1.11.tar.gz"
OPEN_JTALK_DICT_NAME="open_jtalk_dic_utf_8-1.11"
OPEN_DIR="${THIS_DIR}/core/${OPEN_JTALK_DICT_NAME}"
cd ${THIS_DIR}
wget ${CORE_URL}
unzip core.zip
wget ${OPEN_JTALK_DICT_URL}
mkdir ${OPEN_DIR}
tar --strip-components 1 -xvzf ${OPEN_JTALK_DICT_NAME}.tar.gz -C ${OPEN_DIR}
cd ${HOME_DIR}
echo "VOICEVOX_CORE=\"${THIS_DIR}/core/libcore_cpu.so\"" >> /etc/environment

echo "BOT_TOKEN=\"token\"" >> /etc/environment
```

**Comment by Jamu2800** [comment]
環境変数については解決して、dotenv無しでも動くようになりました

エラーは同じものが出力されます

**Comment by Jamu2800** [comment]
node-gypが`npm install`で入っていない気がしたので手動でインストールしました。

ファイルが読み込めないエラーが解消されましたが、新たなエラーが発生しました。
```
/home/jamu/voicevox_discord_tts_bot/node_modules/node-voicevox-engine/index.js:28
        this.addon = new addon(__dirname + '/open_jtalk_dic_utf_8-1.11/', __dirname + '/default.csv', user_dict_root, coreFilePath, useGpu);
                     ^
Error: to load library is succeeded, but can't found needed functions
    at new Engine (/home/jamu/voicevox_discord_tts_bot/node_modules/node-voicevox-engine/index.js:28:22)
    at new TextToSpeechBot (/home/jamu/voicevox_discord_tts_bot/src/textToSpeechBot.ts:228:19)
    at new Client (/home/jamu/voicevox_discord_tts_bot/src/client.ts:8:45)
    at Object.<anonymous> (/home/jamu/voicevox_discord_tts_bot/index.ts:21:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (/home/jamu/voicevox_discord_tts_bot/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jamu/voicevox_discord_tts_bot/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
```

**Comment by Jamu2800** [comment]
ライブラリが読み込めないエラーについては環境変数もしくはvoicevoxコアのバージョンが原因でした
関数が存在しないエラーについては原因不明なのでEngineの方読んでます

**Comment by Jamu2800** [comment]
WSLのUbuntu環境ですがこれで動きました
tokenは自分のものを入力して、`source /etc/environment`してください
voicevox_discord_tts_botの`npm install`だけうまく動かないので自分でお願いします
```sh
#!/bin/bash
echo "apt update"
apt -qq update
echo "apt upgrade"
apt -y -qq upgrade
echo "apt install git-all nodejs npm unzip"
apt install -y -qq git-all nodejs npm unzip
echo "npm install n"
npm install -g n
n lts

THIS_DIR=`pwd`
HOME_DIR="/home/${SUDO_USER}"

# make bot dir
cd ${THIS_DIR}
mkdir tts_bot
INSTALL_DIR="${THIS_DIR}/tts_bot"

# voicevox_discord_tts_bot install
echo "tts bot install"
BOT_URL="https://github.com/y-chan/voicevox_discord_tts_bot.git"
BOT_DIR="${INSTALL_DIR}/voicevox_discord_tts_bot"
cd ${INSTALL_DIR}
echo "git clone"
git clone ${BOT_URL}
cd ${BOT_DIR}
echo "npm install"
# npm install

# onnxruntime install
echo "onnxruntime install"
ONNXRUNTIME_FILE_NAME="onnxruntime"
ONNXRUNTIME_URL="https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-linux-x64-1.10.0.tgz"
ONNXRUNTIME_DIR="${INSTALL_DIR}/${ONNXRUNTIME_FILE_NAME}"
cd ${INSTALL_DIR}
echo "wget onnxruntime"
wget ${ONNXRUNTIME_URL} -O "${ONNXRUNTIME_FILE_NAME}.tgz"
echo "unzip onnxruntime"
mkdir onnxruntime
tar zxf onnxruntime.tgz -C onnxruntime --strip-components 1
echo "set LD_LIBRARY_PATH"
echo "LD_LIBRARY_PATH=\"${LD_LIBRARY_PATH}:${ONNXRUNTIME_DIR}\"" >> /etc/environment

# voicevox_core install
CORE_URL="https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.1/download.sh"
CORE_FILE_NAME="voicevox_core"
CORE_DIR="${INSTALL_DIR}/${CORE_FILE_NAME}"
echo "download installer"
wget ${CORE_URL}
echo "install core"
bash download.sh

# set env
echo "VOICEVOX_CORE=\"${CORE_DIR}/libvoicevox_core.so\"" >> /etc/environment
echo "BOT_TOKEN=\"token\"" >> /etc/environment
```
